DISCIPLINAS = {
    'ACÚSTICA E VIBRAÇÕES VEICULARES': {
        "code": 'FGA0266',
        "name": 'Acústica e Vibrações Veiculares',
        "prerequisites": ['INTRODUÇÃO À ÁLGEBRA LINEAR', 'ONDULATÓRIA E FÍSICA TÉRMICA PARA ENGENHARIA'],
    },
    'AERODINÂMICA DE SISTEMAS AEROESPACIAIS': {
        "code": 'FGA0038',
        "name": 'Aerodinâmica de Sistemas Aeroespaciais',
        "prerequisites": ['DINÂMICA DOS FLUIDOS'],
    },
    'ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES': {
        "code": 'CIC0004',
        "name": 'Algoritmos e Programação de Computadores',
        "prerequisites": [],
    },
    'ANÁLISE ESTRUTURAL MÉTODO DOS ELEMENTOS FINITOS': {
        "code": 'FGA0229',
        "name": 'Análise Estrutural Método dos Elementos Finitos',
        "prerequisites": ['MECÂNICA DOS SÓLIDOS 2 PARA ENGENHARIA'],
    },
    'ARQUITETURA DE MOTORES DE COMBUSTÃO INTERNA': {
        "code": 'FGA0193',
        "name": 'Arquitetura de Motores de Combustão Interna',
        "prerequisites": [],
    },
    'ARQUITETURA E DESENHO DE SOFTWARE': {
        "code": 'FGA0208',
        "name": 'Arquitetura e Desenho de Software',
        "prerequisites": ['REQUISITOS DE SOFTWARE'],
    },
    'CÁLCULO 1': {
        "code": 'MAT0025',
        "name": 'Cálculo 1',
        "prerequisites": [],
    },
    'CÁLCULO 2': {
        "code": 'MAT0026',
        "name": 'Cálculo 2',
        "prerequisites": ['CÁLCULO 1'],
    },
    'CÁLCULO 3': {
        "code": 'MAT0027',
        "name": 'Cálculo 3',
        "prerequisites": ['CÁLCULO 1'],
    },
    'CIÊNCIAS AEROESPACIAIS': {
        "code": 'FGA0254',
        "name": 'Ciências Aeroespaciais',
        "prerequisites": [],
    },
    'COMPILADORES 1': {
        "code": 'FGA0003',
        "name": 'Compiladores 1',
        "prerequisites": ['ESTRUTURAS DE DADOS 1'],
    },
    'DESENHO INDUSTRIAL ASSISTIDO POR COMPUTADOR': {
        "code": 'FGA0168',
        "name": 'Desenho Industrial Assistido por Computador',
        "prerequisites": [],
    },
    'DINÂMICA DE ESTRUTURAS AEROESPACIAIS': {
        "code": 'FGA0050',
        "name": 'Dinâmica de Estruturas Aeroespaciais',
        "prerequisites": ['MECÂNICA DE ESTRUTURAS AEROESPACIAIS', 'SINAIS E SISTEMAS PARA ENGENHARIA'],
    },
    'DINÂMICA DE VEÍCULOS': {
        "code": 'FGA0230',
        "name": 'Dinâmica de Veículos',
        "prerequisites": ['SINAIS E SISTEMAS PARA ENGENHARIA'],
    },
    'DINÂMICA DOS FLUIDOS': {
        "code": 'FGA0204',
        "name": 'Dinâmica dos Fluidos',
        "prerequisites": ['FENÔMENOS DE TRANSPORTE'],
    },
    'DINÂMICA DOS GASES PARA SISTEMAS AEROESPACIAIS': {
        "code": 'FGA0043',
        "name": 'Dinâmica dos Gases para Sistemas Aeroespaciais',
        "prerequisites": ['AERODINÂMICA DE SISTEMAS AEROESPACIAIS'],
    },
    'DINÂMICA DOS MECANISMOS': {
        "code": 'FGA0023',
        "name": 'Dinâmica dos Mecanismos',
        "prerequisites": ['INTRODUÇÃO À ÁLGEBRA LINEAR', 'MECÂNICA DOS SÓLIDOS 1 PARA ENGENHARIA'],
    },
    'ECONOMIA DE ENERGIA': {
        "code": 'FGA0305',
        "name": 'Economia de Energia',
        "prerequisites": [],
    },
    'ELETRÔNICA EMBARCADA': {
        "code": 'FGA0308',
        "name": 'Eletrônica Embarcada',
        "prerequisites": ['TEORIA DE ELETRÔNICA DIGITAL 2', 'PRÁTICA DE ELETRÔNICA DIGITAL 2'],
    },
    'ELETRÔNICA VEICULAR': {
        "code": 'FGA0226',
        "name": 'Eletrônica Veicular',
        "prerequisites": ['TEORIA DE ELETRICIDADE APLICADA', 'LABORATÓRIO DE ELETRICIDADE APLICADA'],
    },
    'ENGENHARIA DE PETRÓLEO E GÁS': {
        "code": 'FGA0175',
        "name": 'Engenharia de Petróleo e Gás',
        "prerequisites": [],
    },
    'ENGENHARIA DE PRODUTO DE SOFTWARE': {
        "code": 'FGA0316',
        "name": 'Engenharia de Produto de Software',
        "prerequisites": ['TÉCNICAS DE PROGRAMAÇÃO EM PLATAFORMAS EMERGENTES'],
    },
    'ENGENHARIA DE SEGURANÇA DO TRABALHO': {
        "code": 'FGA0148',
        "name": 'Engenharia de Segurança do Trabalho',
        "prerequisites": [],
    },
    'ENGENHARIA E AMBIENTE': {
        "code": 'FGA0161',
        "name": 'Engenharia e Ambiente',
        "prerequisites": [],
    },
    'ENGENHARIA ECONÔMICA': {
        "code": 'FGA0133',
        "name": 'Engenharia Econômica',
        "prerequisites": [],
    },
    'EQUIPAMENTOS TERMOFLUIDOS AUTOMOTIVOS': {
        "code": 'FGA0076',
        "name": 'Equipamentos Termofluidos Automotivos',
        "prerequisites": ['FENÔMENOS DE TRANSPORTE', 'ONDULATÓRIA E FÍSICA TÉRMICA PARA ENGENHARIA'],
    },
    'ERGONOMIA DO PRODUTO': {
        "code": 'FGA0152',
        "name": 'Ergonomia do Produto',
        "prerequisites": ['INTRODUÇÃO AO DESIGN E CONCEPÇÃO DE VEÍCULOS'],
    },
    'ESTÁGIO SUPERVISIONADO': {
        "code": 'FGA0288',
        "name": 'Estágio Supervisionado',
        "prerequisites": [],
    },
    'ESTRUTURAS DE DADOS 1': {
        "code": 'FGA0146',
        "name": 'Estruturas de Dados 1',
        "prerequisites": ['ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES'],
    },
    'ESTRUTURAS DE DADOS 2': {
        "code": 'FGA0030',
        "name": 'Estruturas de Dados 2',
        "prerequisites": ['ESTRUTURAS DE DADOS 1'],
    },
    'FENÔMENOS DE TRANSPORTE': {
        "code": 'ENM0080',
        "name": 'Fenômenos de Transporte',
        "prerequisites": ['CÁLCULO 3', 'MECÂNICA DOS SÓLIDOS 1 PARA ENGENHARIA'],
    },
    'FÍSICA 1': {
        "code": 'IFD0171',
        "name": 'Física 1',
        "prerequisites": [],
    },
    'FÍSICA 1 EXPERIMENTAL': {
        "code": 'IFD0173',
        "name": 'Física 1 Experimental',
        "prerequisites": [],
    },
    'FUNDAMENTOS DE ARQUITETURA DE COMPUTADORES': {
        "code": 'FGA0142',
        "name": 'Fundamentos de Arquitetura de Computadores',
        "prerequisites": ['PRÁTICA DE ELETRÔNICA DIGITAL 1', 'TEORIA DE ELETRÔNICA DIGITAL 1'],
    },
    'FUNDAMENTOS DE REDES DE COMPUTADORES': {
        "code": 'FGA0211',
        "name": 'Fundamentos de Redes de Computadores',
        "prerequisites": ['FUNDAMENTOS DE SISTEMAS OPERACIONAIS'],
    },
    'FUNDAMENTOS DE SISTEMAS EMBARCADOS': {
        "code": 'FGA0109',
        "name": 'Fundamentos de Sistemas Embarcados',
        "prerequisites": ['FUNDAMENTOS DE SISTEMAS OPERACIONAIS'],
    },
    'FUNDAMENTOS DE SISTEMAS OPERACIONAIS': {
        "code": 'FGA0170',
        "name": 'Fundamentos de Sistemas Operacionais',
        "prerequisites": ['FUNDAMENTOS DE ARQUITETURA DE COMPUTADORES'],
    },
    'GERÊNCIA DE CONFIGURAÇÃO E EVOLUÇÃO DE SOFTWARE': {
        "code": 'FGA0317',
        "name": 'Gerência de Configuração e Evolução de Software',
        "prerequisites": ['TESTES DE SOFTWARE'],
    },
    'GESTÃO AMBIENTAL NO SETOR ENERGÉTICO': {
        "code": 'FGA0141',
        "name": 'Gestão Ambiental no Setor Energético',
        "prerequisites": ['ENGENHARIA E AMBIENTE', 'GESTÃO DA PRODUÇÃO E QUALIDADE'],
    },
    'GESTÃO DA PRODUÇÃO E QUALIDADE': {
        "code": 'FGA0184',
        "name": 'Gestão da Produção e Qualidade',
        "prerequisites": ['ENGENHARIA ECONÔMICA'],
    },
    'HUMANIDADES E CIDADANIA': {
        "code": 'FGA0164',
        "name": 'Humanidades e Cidadania',
        "prerequisites": [],
    },
    'IMPACTOS SOCIAIS DA ENGENHARIA AEROESPACIAL': {
        "code": 'FGA0294',
        "name": 'Impactos Sociais da Engenharia Aeroespacial',
        "prerequisites": ['MECÂNICA DE ESTRUTURAS AEROESPACIAIS'],
    },
    'INSTRUMENTAÇÃO ELETRÔNICA PARA ENGENHARIA': {
        "code": 'FGA0132',
        "name": 'Instrumentação Eletrônica para Engenharia',
        "prerequisites": ['TEORIA DE CIRCUITOS ELETRÔNICOS 2', 'PRÁTICA DE CIRCUITOS ELETRÔNICOS 2'],
    },
    'INTERAÇÃO HUMANO COMPUTADOR': {
        "code": 'FGA0173',
        "name": 'Interação Humano Computador',
        "prerequisites": ['MÉTODOS DE DESENVOLVIMENTO DE SOFTWARE'],
    },
    'INTRODUÇÃO À ÁLGEBRA LINEAR': {
        "code": 'MAT0031',
        "name": 'Introdução à Álgebra Linear',
        "prerequisites": [],
    },
    'INTRODUÇÃO À ENGENHARIA': {
        "code": 'FGA0163',
        "name": 'Introdução à Engenharia',
        "prerequisites": [],
    },
    'INTRODUÇÃO AO DESIGN E CONCEPÇÃO DE VEÍCULOS': {
        "code": 'FGA0155',
        "name": 'Introdução ao Design e Concepção de Veículos',
        "prerequisites": ['DESENHO INDUSTRIAL ASSISTIDO POR COMPUTADOR'],
    },
    'LABORATÓRIO DE ELETRICIDADE APLICADA': {
        "code": 'FGA0087',
        "name": 'Laboratório de Eletricidade Aplicada',
        "prerequisites": ['SINAIS E SISTEMAS PARA ENGENHARIA'],
    },
    'LABORATÓRIO DE MATERIAIS DE CONSTRUÇÃO': {
        "code": 'FGA0075',
        "name": 'Laboratório de Materiais de Construção',
        "prerequisites": ['QUÍMICA GERAL TEÓRICA', 'QUÍMICA GERAL EXPERIMENTAL'],
    },
    'LABORATÓRIO DE ONDULATÓRIA E FÍSICA TÉRMICA PARA A ENGENHARIA': {
        "code": 'FGA0107',
        "name": 'Laboratório de Ondulatória e Física Térmica para a Engenharia',
        "prerequisites": ['FÍSICA 1', 'FÍSICA 1 EXPERIMENTAL'],
    },
    'LABORATÓRIO DE SISTEMAS DE CONVERSÃO DE ENERGIA': {
        "code": 'FGA0089',
        "name": 'Laboratório de Sistemas de Conversão de Energia',
        "prerequisites": ['TEORIA DE ELETRICIDADE APLICADA', 'LABORATÓRIO DE ELETRICIDADE APLICADA'],
    },
    'MÁQUINAS DE FLUIDO': {
        "code": 'FGA0091',
        "name": 'Máquinas de Fluido',
        "prerequisites": ['DINÂMICA DOS FLUIDOS'],
    },
    'MATEMÁTICA DISCRETA 1': {
        "code": 'FGA0085',
        "name": 'Matemática Discreta 1',
        "prerequisites": [],
    },
    'MATEMÁTICA DISCRETA 2': {
        "code": 'FGA0108',
        "name": 'Matemática Discreta 2',
        "prerequisites": ['MATEMÁTICA DISCRETA 1'],
    },
    'MATERIAIS COMPOSTOS E PLÁSTICOS': {
        "code": 'FGA0191',
        "name": 'Materiais Compostos e Plásticos',
        "prerequisites": ['LABORATÓRIO DE MATERIAIS DE CONSTRUÇÃO', 'TEORIA DE MATERIAIS DE CONSTRUÇÃO'],
    },
    'MECÂNICA DE ESTRUTURAS AEROESPACIAIS': {
        "code": 'FGA0039',
        "name": 'Mecânica de Estruturas Aeroespaciais',
        "prerequisites": ['MECÂNICA DOS SÓLIDOS 2 PARA ENGENHARIA'],
    },
    'MECÂNICA DO VOO': {
        "code": 'FGA0045',
        "name": 'Mecânica do Voo',
        "prerequisites": ['SISTEMAS AEROESPACIAIS', 'AERODINÂMICA DE SISTEMAS AEROESPACIAIS'],
    },
    'MECÂNICA DO VOO ESPACIAL': {
        "code": 'FGA0048',
        "name": 'Mecânica do Voo Espacial',
        "prerequisites": ['MECÂNICA DO VOO'],
    },
    'MECÂNICA DOS SÓLIDOS 1 PARA ENGENHARIA': {
        "code": 'FGA0154',
        "name": 'Mecânica dos Sólidos 1 para Engenharia',
        "prerequisites": ['FÍSICA 1'],
    },
    'MECÂNICA DOS SÓLIDOS 2 PARA ENGENHARIA': {
        "code": 'FGA0179',
        "name": 'Mecânica dos Sólidos 2 para Engenharia',
        "prerequisites": ['MECÂNICA DOS SÓLIDOS 1 PARA ENGENHARIA', 'INTRODUÇÃO À ÁLGEBRA LINEAR'],
    },
    'MÉTODOS DE DESENVOLVIMENTO DE SOFTWARE': {
        "code": 'FGA0312',
        "name": 'Métodos de Desenvolvimento de Software',
        "prerequisites": ['ORIENTAÇÃO A OBJETOS'],
    },
    'MÉTODOS EXPERIMENTAIS PARA ENGENHARIA': {
        "code": 'FGA0188',
        "name": 'Métodos Experimentais para Engenharia',
        "prerequisites": ['FÍSICA 1 EXPERIMENTAL'],
    },
    'MÉTODOS NUMÉRICOS PARA ENGENHARIA': {
        "code": 'FGA0160',
        "name": 'Métodos Numéricos para Engenharia',
        "prerequisites": ['CÁLCULO 2'],
    },
    'ONDULATÓRIA E FÍSICA TÉRMICA PARA ENGENHARIA': {
        "code": 'FGA0090',
        "name": 'Ondulatória e Física Térmica para Engenharia',
        "prerequisites": ['CÁLCULO 1', 'FÍSICA 1', 'FÍSICA 1 EXPERIMENTAL'],
    },
    'ORIENTAÇÃO A OBJETOS': {
        "code": 'FGA0158',
        "name": 'Orientação a Objetos',
        "prerequisites": ['ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES'],
    },
    'PARADIGMAS DE PROGRAMAÇÃO': {
        "code": 'FGA0210',
        "name": 'Paradigmas de Programação',
        "prerequisites": ['ORIENTAÇÃO A OBJETOS', 'COMPILADORES 1'],
    },
    'PRÁTICA DE CIRCUITOS ELETRÔNICOS 1': {
        "code": 'FGA0069',
        "name": 'Prática de Circuitos Eletrônicos 1',
        "prerequisites": ['CÁLCULO 2'],
    },
    'PRÁTICA DE CIRCUITOS ELETRÔNICOS 2': {
        "code": 'FGA0070',
        "name": 'Prática de Circuitos Eletrônicos 2',
        "prerequisites": [
            'TEORIA DE CIRCUITOS ELETRÔNICOS 1',
            'PRÁTICA DE CIRCUITOS ELETRÔNICOS 1',
            'TEORIA DE FÍSICA DOS DISPOSITIVOS ELETRÔNICOS',
            'PRÁTICA DE FÍSICA DOS DISPOSITIVOS ELETRÔNICOS',
        ],
    },
    'PRÁTICA DE CIRCUITOS ELETRÔNICOS 3': {
        "code": 'FGA0098',
        "name": 'Prática de Circuitos Eletrônicos 3',
        "prerequisites": ['PROJETOS DE CIRCUITOS INTEGRADOS 1'],
    },
    'PRÁTICA DE ELETROMAGNETISMO': {
        "code": 'FGA0120',
        "name": 'Prática de Eletromagnetismo',
        "prerequisites": ['FÍSICA 1', 'CÁLCULO 3'],
    },
    'PRÁTICA DE ELETRÔNICA DIGITAL 1': {
        "code": 'FGA0071',
        "name": 'Prática de Eletrônica Digital 1',
        "prerequisites": ['INTRODUÇÃO À ÁLGEBRA LINEAR'],
    },
    'PRÁTICA DE ELETRÔNICA DIGITAL 2': {
        "code": 'FGA0072',
        "name": 'Prática de Eletrônica Digital 2',
        "prerequisites": ['TEORIA DE ELETRÔNICA DIGITAL 1', 'PRÁTICA DE ELETRÔNICA DIGITAL 1'],
    },
    'PRÁTICA DE FÍSICA DOS DISPOSITIVOS ELETRÔNICOS': {
        "code": 'FGA0100',
        "name": 'Prática de Física dos Dispositivos Eletrônicos',
        "prerequisites": ['TEORIA DE ELETROMAGNETISMO', 'PRÁTICA DE ELETROMAGNETISMO'],
    },
    'PRINCÍPIOS DE COMUNICAÇÃO PARA ENGENHARIA': {
        "code": 'FGA0092',
        "name": 'Princípios de Comunicação para Engenharia',
        "prerequisites": ['SINAIS E SISTEMAS PARA ENGENHARIA', 'TEORIA DE CIRCUITOS ELETRÔNICOS 1'],
    },
    'PRINCÍPIOS DE CONTROLE': {
        "code": 'FGA0093',
        "name": 'Princípios de Controle',
        "prerequisites": ['SINAIS E SISTEMAS PARA ENGENHARIA'],
    },
    'PROBABILIDADE E ESTATÍSTICA APLICADO À ENGENHARIA': {
        "code": 'FGA0157',
        "name": 'Probabilidade e Estatística Aplicado à Engenharia',
        "prerequisites": ['CÁLCULO 1'],
    },
    'PROCESSAMENTO DE SINAIS': {
        "code": 'FGA0219',
        "name": 'Processamento de Sinais',
        "prerequisites": ['SINAIS E SISTEMAS PARA ENGENHARIA'],
    },
    'PROGRAMAÇÃO PARA SISTEMAS PARALELOS E DISTRIBUÍDOS': {
        "code": 'FGA0244',
        "name": 'Programação para Sistemas Paralelos e Distribuídos',
        "prerequisites": ['FUNDAMENTOS DE REDES DE COMPUTADORES', 'ESTRUTURAS DE DADOS 2'],
    },
    'PROJETO DE ALGORITMOS': {
        "code": 'FGA0124',
        "name": 'Projeto de Algoritmos',
        "prerequisites": ['ESTRUTURAS DE DADOS 1'],
    },
    'PROJETOS DE CIRCUITOS INTEGRADOS 1': {
        "code": 'FGA0017',
        "name": 'Projetos de Circuitos Integrados 1',
        "prerequisites": ['TEORIA DE CIRCUITOS ELETRÔNICOS 2', 'PRÁTICA DE CIRCUITOS ELETRÔNICOS 2'],
    },
    'PROJETO DE ELEMENTOS AUTOMOTIVOS': {
        "code": 'FGA0190',
        "name": 'Projeto de Elementos Automotivos',
        "prerequisites": ['MECÂNICA DOS SÓLIDOS 2 PARA ENGENHARIA'],
    },
    'PROJETO DE ESTRUTURAS DE VEÍCULOS': {
        "code": 'FGA0267',
        "name": 'Projeto de Estruturas de Veículos',
        "prerequisites": ['PROJETO DE SISTEMAS AUTOMOTIVOS'],
    },
    'PROJETO DE SISTEMAS AUTOMOTIVOS': {
        "code": 'FGA0228',
        "name": 'Projeto de Sistemas Automotivos',
        "prerequisites": ['PROJETO DE ELEMENTOS AUTOMOTIVOS'],
    },
    'PROJETO INTEGRADOR DE ENGENHARIA 1': {
        "code": 'FGA0150',
        "name": 'Projeto Integrador de Engenharia 1',
        "prerequisites": [],
    },
    'PROJETO INTEGRADOR DE ENGENHARIA 2': {
        "code": 'FGA0250',
        "name": 'Projeto Integrador de Engenharia 2',
        "prerequisites": ['PROJETO INTEGRADOR DE ENGENHARIA 1'],
    },
    'PROPULSÃO AEROESPACIAL': {
        "code": 'FGA0052',
        "name": 'Propulsão Aeroespacial',
        "prerequisites": ['DINÂMICA DOS GASES PARA SISTEMAS AEROESPACIAIS'],
    },
    'QUALIDADE DE SOFTWARE 1': {
        "code": 'FGA0315',
        "name": 'Qualidade de Software 1',
        "prerequisites": [],
    },
    'QUÍMICA GERAL EXPERIMENTAL': {
        "code": 'IQD0126',
        "name": 'Química Geral Experimental',
        "prerequisites": [],
    },
    'QUÍMICA GERAL TEÓRICA': {
        "code": 'IQD0125',
        "name": 'Química Geral Teórica',
        "prerequisites": [],
    },
    'QUÍMICA ORGÂNICA APLICADA À ENGENHARIA': {
        "code": 'FGA0104',
        "name": 'Química Orgânica Aplicada à Engenharia',
        "prerequisites": ['QUÍMICA GERAL TEÓRICA', 'QUÍMICA GERAL EXPERIMENTAL'],
    },
    'REQUISITOS DE SOFTWARE': {
        "code": 'FGA0313',
        "name": 'Requisitos de Software',
        "prerequisites": ['MÉTODOS DE DESENVOLVIMENTO DE SOFTWARE'],
    },
    'SINAIS E SISTEMAS PARA ENGENHARIA': {
        "code": 'FGA0102',
        "name": 'Sinais e Sistemas para Engenharia',
        "prerequisites": ['CÁLCULO 3', 'ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES'],
    },
    'SISTEMAS AEROESPACIAIS': {
        "code": 'FGA0008',
        "name": 'Sistemas Aeroespaciais',
        "prerequisites": ['FÍSICA 1', 'CIÊNCIAS AEROESPACIAIS'],
    },
    'SISTEMAS DE BANCO DE DADOS 1': {
        "code": 'FGA0137',
        "name": 'Sistemas de Banco de Dados 1',
        "prerequisites": ['MATEMÁTICA DISCRETA 2'],
    },
    'SISTEMAS DE BANCO DE DADOS 2': {
        "code": 'FGA0060',
        "name": 'Sistemas de Banco de Dados 2',
        "prerequisites": ['SISTEMAS DE BANCO DE DADOS 1'],
    },
    'SISTEMAS DE ENERGIA SOLAR E EÓLICA': {
        "code": 'FGA0025',
        "name": 'Sistemas de Energia Solar e Eólica',
        "prerequisites": ['TEORIA DE ELETRICIDADE APLICADA', 'LABORATÓRIO DE ELETRICIDADE APLICADA'],
    },
    'SISTEMAS HIDROELÉTRICOS': {
        "code": 'FGA0329',
        "name": 'Sistemas Hidroelétricos',
        "prerequisites": ['MÁQUINAS DE FLUIDO'],
    },
    'SISTEMAS OPERACIONAIS EMBARCADOS': {
        "code": 'FGA0309',
        "name": 'Sistemas Operacionais Embarcados',
        "prerequisites": ['ELETRÔNICA EMBARCADA'],
    },
    'TÉCNICAS DE PROGRAMAÇÃO EM PLATAFORMAS EMERGENTES': {
        "code": 'FGA0242',
        "name": 'Técnicas de Programação em Plataformas Emergentes',
        "prerequisites": ['ARQUITETURA E DESENHO DE SOFTWARE', 'TESTES DE SOFTWARE'],
    },
    'TECNOLOGIAS DE FABRICAÇÃO 1': {
        "code": 'FGA0055',
        "name": 'Tecnologias de Fabricação 1',
        "prerequisites": ['TEORIA DE MATERIAIS DE CONSTRUÇÃO', 'LABORATÓRIO DE MATERIAIS DE CONSTRUÇÃO'],
    },
    'TECNOLOGIAS DE FABRICAÇÃO 2': {
        "code": 'FGA0056',
        "name": 'Tecnologias de Fabricação 2',
        "prerequisites": ['TEORIA DE MATERIAIS DE CONSTRUÇÃO', 'LABORATÓRIO DE MATERIAIS DE CONSTRUÇÃO'],
    },
    'TEORIA DE CIRCUITOS ELETRÔNICOS 1': {
        "code": 'FGA0067',
        "name": 'Teoria de Circuitos Eletrônicos 1',
        "prerequisites": ['CÁLCULO 2'],
    },
    'TEORIA DE CIRCUITOS ELETRÔNICOS 2': {
        "code": 'FGA0068',
        "name": 'Teoria de Circuitos Eletrônicos 2',
        "prerequisites": [
            'TEORIA DE CIRCUITOS ELETRÔNICOS 1',
            'PRÁTICA DE CIRCUITOS ELETRÔNICOS 1',
            'TEORIA DE FÍSICA DOS DISPOSITIVOS ELETRÔNICOS',
            'PRÁTICA DE FÍSICA DOS DISPOSITIVOS ELETRÔNICOS',
        ],
    },
    'TEORIA DE CIRCUITOS ELETRÔNICOS 3': {
        "code": 'FGA0099',
        "name": 'Teoria de Circuitos Eletrônicos 3',
        "prerequisites": ['PROJETOS DE CIRCUITOS INTEGRADOS 1'],
    },
    'TEORIA DE ELETRICIDADE APLICADA': {
        "code": 'FGA0086',
        "name": 'Teoria de Eletricidade Aplicada',
        "prerequisites": ['SINAIS E SISTEMAS PARA ENGENHARIA'],
    },
    'TEORIA DE ELETROMAGNETISMO': {
        "code": 'FGA0119',
        "name": 'Teoria de Eletromagnetismo',
        "prerequisites": ['FÍSICA 1', 'CÁLCULO 3'],
    },
    'TEORIA DE ELETRÔNICA DIGITAL 1': {
        "code": 'FGA0073',
        "name": 'Teoria de Eletrônica Digital 1',
        "prerequisites": ['INTRODUÇÃO À ÁLGEBRA LINEAR'],
    },
    'TEORIA DE ELETRÔNICA DIGITAL 2': {
        "code": 'FGA0074',
        "name": 'Teoria de Eletrônica Digital 2',
        "prerequisites": ['TEORIA DE ELETRÔNICA DIGITAL 1', 'PRÁTICA DE ELETRÔNICA DIGITAL 1'],
    },
    'TEORIA DE FÍSICA DOS DISPOSITIVOS ELETRÔNICOS': {
        "code": 'FGA0101',
        "name": 'Teoria de Física dos Dispositivos Eletrônicos',
        "prerequisites": ['TEORIA DE ELETROMAGNETISMO', 'PRÁTICA DE ELETROMAGNETISMO'],
    },
    'TEORIA DE MATERIAIS DE CONSTRUÇÃO': {
        "code": 'FGA0078',
        "name": 'Teoria de Materiais de Construção',
        "prerequisites": ['QUÍMICA GERAL TEÓRICA', 'QUÍMICA GERAL EXPERIMENTAL'],
    },
    'TEORIA DE SISTEMAS DE CONVERSÃO DE ENERGIA': {
        "code": 'FGA0088',
        "name": 'Teoria de Sistemas de Conversão de Energia',
        "prerequisites": ['TEORIA DE ELETRICIDADE APLICADA', 'LABORATÓRIO DE ELETRICIDADE APLICADA'],
    },
    'TERMODINÂMICA 1': {
        "code": 'ENM0068',
        "name": 'Termodinâmica 1',
        "prerequisites": ['FENÔMENOS DE TRANSPORTE'],
    },
    'TESTES DE SOFTWARE': {
        "code": 'FGA0314',
        "name": 'Testes de Software',
        "prerequisites": ['MÉTODOS DE DESENVOLVIMENTO DE SOFTWARE'],
    },
    'TRABALHO DE CONCLUSÃO DE CURSO 1': {
        "code": 'FGA0287',
        "name": 'Trabalho de Conclusão de Curso 1',
        "prerequisites": [],
    },
    'TRABALHO DE CONCLUSÃO DE CURSO 2': {
        "code": 'FGA0290',
        "name": 'Trabalho de Conclusão de Curso 2',
        "prerequisites": ['TRABALHO DE CONCLUSÃO DE CURSO 1'],
    },
    'TRANSFERÊNCIA DE CALOR': {
        "code": 'ENM0071',
        "name": 'Transferência de Calor',
        "prerequisites": ['TERMODINÂMICA 1', 'DINÂMICA DOS FLUIDOS'],
    },
    'TRANSMISSÃO E DISTRIBUIÇÃO DE ENERGIA ELÉTRICA': {
        "code": 'FGA0262',
        "name": 'Transmissão e Distribuição de Energia Elétrica',
        "prerequisites": ['TEORIA DE ELETRICIDADE APLICADA', 'LABORATÓRIO DE ELETRICIDADE APLICADA'],
    },
}


CURSOS = {
    'AEROESPACIAL': {
        "name": 'Engenharia Aeroespacial',
        "subjects": [
            'AERODINÂMICA DE SISTEMAS AEROESPACIAIS',
            'ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES',
            'CÁLCULO 1',
            'CÁLCULO 2',
            'CÁLCULO 3',
            'CIÊNCIAS AEROESPACIAIS',
            'DESENHO INDUSTRIAL ASSISTIDO POR COMPUTADOR',
            'DINÂMICA DE ESTRUTURAS AEROESPACIAIS',
            'DINÂMICA DOS FLUIDOS',
            'DINÂMICA DOS GASES PARA SISTEMAS AEROESPACIAIS',
            'ENGENHARIA DE SEGURANÇA DO TRABALHO',
            'ENGENHARIA E AMBIENTE',
            'ENGENHARIA ECONÔMICA',
            'ESTÁGIO SUPERVISIONADO',
            'FENÔMENOS DE TRANSPORTE',
            'FÍSICA 1',
            'FÍSICA 1 EXPERIMENTAL',
            'GESTÃO DA PRODUÇÃO E QUALIDADE',
            'HUMANIDADES E CIDADANIA',
            'IMPACTOS SOCIAIS DA ENGENHARIA AEROESPACIAL',
            'INTRODUÇÃO À ÁLGEBRA LINEAR',
            'INTRODUÇÃO À ENGENHARIA',
            'LABORATÓRIO DE ELETRICIDADE APLICADA',
            'LABORATÓRIO DE MATERIAIS DE CONSTRUÇÃO',
            'MECÂNICA DE ESTRUTURAS AEROESPACIAIS',
            'MECÂNICA DO VOO',
            'MECÂNICA DO VOO ESPACIAL',
            'MECÂNICA DOS SÓLIDOS 1 PARA ENGENHARIA',
            'MECÂNICA DOS SÓLIDOS 2 PARA ENGENHARIA',
            'MÉTODOS NUMÉRICOS PARA ENGENHARIA',
            'PRÁTICA DE ELETROMAGNETISMO',
            'PRINCÍPIOS DE CONTROLE',
            'PROBABILIDADE E ESTATÍSTICA APLICADO À ENGENHARIA',
            'PROJETO INTEGRADOR DE ENGENHARIA 1',
            'PROJETO INTEGRADOR DE ENGENHARIA 2',
            'PROPULSÃO AEROESPACIAL',
            'QUÍMICA GERAL EXPERIMENTAL',
            'QUÍMICA GERAL TEÓRICA',
            'SINAIS E SISTEMAS PARA ENGENHARIA',
            'SISTEMAS AEROESPACIAIS',
            'TEORIA DE ELETRICIDADE APLICADA',
            'TEORIA DE ELETROMAGNETISMO',
            'TEORIA DE MATERIAIS DE CONSTRUÇÃO',
            'TERMODINÂMICA 1',
            'TRABALHO DE CONCLUSÃO DE CURSO 1',
            'TRABALHO DE CONCLUSÃO DE CURSO 2',
            'TRANSFERÊNCIA DE CALOR',
        ],
    },
    'AUTOMOTIVA': {
        "name": 'Engenharia Automotiva',
        "subjects": [
            'ACÚSTICA E VIBRAÇÕES VEICULARES',
            'ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES',
            'ANÁLISE ESTRUTURAL MÉTODO DOS ELEMENTOS FINITOS',
            'ARQUITETURA DE MOTORES DE COMBUSTÃO INTERNA',
            'CÁLCULO 1',
            'CÁLCULO 2',
            'CÁLCULO 3',
            'DESENHO INDUSTRIAL ASSISTIDO POR COMPUTADOR',
            'DINÂMICA DE VEÍCULOS',
            'DINÂMICA DOS MECANISMOS',
            'ELETRÔNICA VEICULAR',
            'ENGENHARIA DE SEGURANÇA DO TRABALHO',
            'ENGENHARIA E AMBIENTE',
            'ENGENHARIA ECONÔMICA',
            'EQUIPAMENTOS TERMOFLUIDOS AUTOMOTIVOS',
            'ERGONOMIA DO PRODUTO',
            'ESTÁGIO SUPERVISIONADO',
            'FENÔMENOS DE TRANSPORTE',
            'FÍSICA 1',
            'FÍSICA 1 EXPERIMENTAL',
            'GESTÃO DA PRODUÇÃO E QUALIDADE',
            'HUMANIDADES E CIDADANIA',
            'INTRODUÇÃO À ÁLGEBRA LINEAR',
            'INTRODUÇÃO À ENGENHARIA',
            'INTRODUÇÃO AO DESIGN E CONCEPÇÃO DE VEÍCULOS',
            'LABORATÓRIO DE ELETRICIDADE APLICADA',
            'LABORATÓRIO DE MATERIAIS DE CONSTRUÇÃO',
            'LABORATÓRIO DE ONDULATÓRIA E FÍSICA TÉRMICA PARA A ENGENHARIA',
            'MATERIAIS COMPOSTOS E PLÁSTICOS',
            'MECÂNICA DOS SÓLIDOS 1 PARA ENGENHARIA',
            'MECÂNICA DOS SÓLIDOS 2 PARA ENGENHARIA',
            'MÉTODOS EXPERIMENTAIS PARA ENGENHARIA',
            'MÉTODOS NUMÉRICOS PARA ENGENHARIA',
            'ONDULATÓRIA E FÍSICA TÉRMICA PARA ENGENHARIA',
            'PRÁTICA DE CIRCUITOS ELETRÔNICOS 1',
            'PROBABILIDADE E ESTATÍSTICA APLICADO À ENGENHARIA',
            'PROJETO DE ELEMENTOS AUTOMOTIVOS',
            'PROJETO DE ESTRUTURAS DE VEÍCULOS',
            'PROJETO DE SISTEMAS AUTOMOTIVOS',
            'PROJETO INTEGRADOR DE ENGENHARIA 1',
            'PROJETO INTEGRADOR DE ENGENHARIA 2',
            'QUÍMICA GERAL EXPERIMENTAL',
            'QUÍMICA GERAL TEÓRICA',
            'SINAIS E SISTEMAS PARA ENGENHARIA',
            'TECNOLOGIAS DE FABRICAÇÃO 1',
            'TECNOLOGIAS DE FABRICAÇÃO 2',
            'TEORIA DE CIRCUITOS ELETRÔNICOS 1',
            'TEORIA DE ELETRICIDADE APLICADA',
            'TEORIA DE MATERIAIS DE CONSTRUÇÃO',
            'TRABALHO DE CONCLUSÃO DE CURSO 1',
            'TRABALHO DE CONCLUSÃO DE CURSO 2',
        ],
    },
    'ENERGIA': {
        "name": 'Engenharia de Energia',
        "subjects": [
            'ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES',
            'CÁLCULO 1',
            'CÁLCULO 2',
            'CÁLCULO 3',
            'DESENHO INDUSTRIAL ASSISTIDO POR COMPUTADOR',
            'DINÂMICA DOS FLUIDOS',
            'ECONOMIA DE ENERGIA',
            'ENGENHARIA DE PETRÓLEO E GÁS',
            'ENGENHARIA DE SEGURANÇA DO TRABALHO',
            'ENGENHARIA E AMBIENTE',
            'ENGENHARIA ECONÔMICA',
            'ESTÁGIO SUPERVISIONADO',
            'FENÔMENOS DE TRANSPORTE',
            'FÍSICA 1',
            'FÍSICA 1 EXPERIMENTAL',
            'GESTÃO AMBIENTAL NO SETOR ENERGÉTICO',
            'GESTÃO DA PRODUÇÃO E QUALIDADE',
            'HUMANIDADES E CIDADANIA',
            'INTRODUÇÃO À ÁLGEBRA LINEAR',
            'INTRODUÇÃO À ENGENHARIA',
            'LABORATÓRIO DE ELETRICIDADE APLICADA',
            'LABORATÓRIO DE MATERIAIS DE CONSTRUÇÃO',
            'LABORATÓRIO DE SISTEMAS DE CONVERSÃO DE ENERGIA',
            'MÁQUINAS DE FLUIDO',
            'MECÂNICA DOS SÓLIDOS 1 PARA ENGENHARIA',
            'MÉTODOS NUMÉRICOS PARA ENGENHARIA',
            'PRÁTICA DE CIRCUITOS ELETRÔNICOS 1',
            'PRÁTICA DE ELETROMAGNETISMO',
            'PROBABILIDADE E ESTATÍSTICA APLICADO À ENGENHARIA',
            'PROJETO INTEGRADOR DE ENGENHARIA 1',
            'PROJETO INTEGRADOR DE ENGENHARIA 2',
            'QUÍMICA GERAL EXPERIMENTAL',
            'QUÍMICA GERAL TEÓRICA',
            'QUÍMICA ORGÂNICA APLICADA À ENGENHARIA',
            'SINAIS E SISTEMAS PARA ENGENHARIA',
            'SISTEMAS DE ENERGIA SOLAR E EÓLICA',
            'SISTEMAS HIDROELÉTRICOS',
            'TEORIA DE CIRCUITOS ELETRÔNICOS 1',
            'TEORIA DE ELETRICIDADE APLICADA',
            'TEORIA DE ELETROMAGNETISMO',
            'TEORIA DE MATERIAIS DE CONSTRUÇÃO',
            'TEORIA DE SISTEMAS DE CONVERSÃO DE ENERGIA',
            'TERMODINÂMICA 1',
            'TRABALHO DE CONCLUSÃO DE CURSO 1',
            'TRABALHO DE CONCLUSÃO DE CURSO 2',
            'TRANSFERÊNCIA DE CALOR',
            'TRANSMISSÃO E DISTRIBUIÇÃO DE ENERGIA ELÉTRICA',
        ],
    },
    'SOFTWARE': {
        "name": 'Engenharia de Software',
        "subjects": [
            'ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES',
            'ARQUITETURA E DESENHO DE SOFTWARE',
            'CÁLCULO 1',
            'CÁLCULO 2',
            'COMPILADORES 1',
            'DESENHO INDUSTRIAL ASSISTIDO POR COMPUTADOR',
            'ENGENHARIA DE PRODUTO DE SOFTWARE',
            'ENGENHARIA E AMBIENTE',
            'ENGENHARIA ECONÔMICA',
            'ESTÁGIO SUPERVISIONADO',
            'ESTRUTURAS DE DADOS 1',
            'ESTRUTURAS DE DADOS 2',
            'FÍSICA 1',
            'FÍSICA 1 EXPERIMENTAL',
            'FUNDAMENTOS DE ARQUITETURA DE COMPUTADORES',
            'FUNDAMENTOS DE REDES DE COMPUTADORES',
            'FUNDAMENTOS DE SISTEMAS EMBARCADOS',
            'FUNDAMENTOS DE SISTEMAS OPERACIONAIS',
            'GERÊNCIA DE CONFIGURAÇÃO E EVOLUÇÃO DE SOFTWARE',
            'GESTÃO DA PRODUÇÃO E QUALIDADE',
            'HUMANIDADES E CIDADANIA',
            'INTERAÇÃO HUMANO COMPUTADOR',
            'INTRODUÇÃO À ÁLGEBRA LINEAR',
            'INTRODUÇÃO À ENGENHARIA',
            'MATEMÁTICA DISCRETA 1',
            'MATEMÁTICA DISCRETA 2',
            'MÉTODOS DE DESENVOLVIMENTO DE SOFTWARE',
            'MÉTODOS NUMÉRICOS PARA ENGENHARIA',
            'ORIENTAÇÃO A OBJETOS',
            'PARADIGMAS DE PROGRAMAÇÃO',
            'PRÁTICA DE ELETRÔNICA DIGITAL 1',
            'PROBABILIDADE E ESTATÍSTICA APLICADO À ENGENHARIA',
            'PROGRAMAÇÃO PARA SISTEMAS PARALELOS E DISTRIBUÍDOS',
            'PROJETO DE ALGORITMOS',
            'PROJETO INTEGRADOR DE ENGENHARIA 1',
            'PROJETO INTEGRADOR DE ENGENHARIA 2',
            'QUALIDADE DE SOFTWARE 1',
            'REQUISITOS DE SOFTWARE',
            'SISTEMAS DE BANCO DE DADOS 1',
            'SISTEMAS DE BANCO DE DADOS 2',
            'TÉCNICAS DE PROGRAMAÇÃO EM PLATAFORMAS EMERGENTES',
            'TEORIA DE ELETRÔNICA DIGITAL 1',
            'TESTES DE SOFTWARE',
            'TRABALHO DE CONCLUSÃO DE CURSO 1',
            'TRABALHO DE CONCLUSÃO DE CURSO 2',
        ],
    },
    'ELETRONICA': {
        "name": 'Engenharia Eletrônica',
        "subjects": [
            'ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES',
            'CÁLCULO 1',
            'CÁLCULO 2',
            'CÁLCULO 3',
            'DESENHO INDUSTRIAL ASSISTIDO POR COMPUTADOR',
            'ELETRÔNICA EMBARCADA',
            'ENGENHARIA DE SEGURANÇA DO TRABALHO',
            'ENGENHARIA E AMBIENTE',
            'ENGENHARIA ECONÔMICA',
            'ESTÁGIO SUPERVISIONADO',
            'FENÔMENOS DE TRANSPORTE',
            'FÍSICA 1',
            'FÍSICA 1 EXPERIMENTAL',
            'GESTÃO DA PRODUÇÃO E QUALIDADE',
            'HUMANIDADES E CIDADANIA',
            'INSTRUMENTAÇÃO ELETRÔNICA PARA ENGENHARIA',
            'INTRODUÇÃO À ÁLGEBRA LINEAR',
            'INTRODUÇÃO À ENGENHARIA',
            'LABORATÓRIO DE ELETRICIDADE APLICADA',
            'LABORATÓRIO DE MATERIAIS DE CONSTRUÇÃO',
            'MECÂNICA DOS SÓLIDOS 1 PARA ENGENHARIA',
            'MÉTODOS NUMÉRICOS PARA ENGENHARIA',
            'PRÁTICA DE CIRCUITOS ELETRÔNICOS 1',
            'PRÁTICA DE CIRCUITOS ELETRÔNICOS 2',
            'PRÁTICA DE CIRCUITOS ELETRÔNICOS 3',
            'PRÁTICA DE ELETROMAGNETISMO',
            'PRÁTICA DE ELETRÔNICA DIGITAL 1',
            'PRÁTICA DE ELETRÔNICA DIGITAL 2',
            'PRÁTICA DE FÍSICA DOS DISPOSITIVOS ELETRÔNICOS',
            'PRINCÍPIOS DE COMUNICAÇÃO PARA ENGENHARIA',
            'PRINCÍPIOS DE CONTROLE',
            'PROBABILIDADE E ESTATÍSTICA APLICADO À ENGENHARIA',
            'PROCESSAMENTO DE SINAIS',
            'PROJETO INTEGRADOR DE ENGENHARIA 1',
            'PROJETO INTEGRADOR DE ENGENHARIA 2',
            'PROJETOS DE CIRCUITOS INTEGRADOS 1',
            'QUÍMICA GERAL EXPERIMENTAL',
            'QUÍMICA GERAL TEÓRICA',
            'SINAIS E SISTEMAS PARA ENGENHARIA',
            'SISTEMAS OPERACIONAIS EMBARCADOS',
            'TEORIA DE CIRCUITOS ELETRÔNICOS 1',
            'TEORIA DE CIRCUITOS ELETRÔNICOS 2',
            'TEORIA DE CIRCUITOS ELETRÔNICOS 3',
            'TEORIA DE ELETRICIDADE APLICADA',
            'TEORIA DE ELETROMAGNETISMO',
            'TEORIA DE ELETRÔNICA DIGITAL 1',
            'TEORIA DE ELETRÔNICA DIGITAL 2',
            'TEORIA DE FÍSICA DOS DISPOSITIVOS ELETRÔNICOS',
            'TEORIA DE MATERIAIS DE CONSTRUÇÃO',
            'TRABALHO DE CONCLUSÃO DE CURSO 1',
            'TRABALHO DE CONCLUSÃO DE CURSO 2',
        ],
    },
}


def get_subjects_by_course(course_id: str) -> list[dict]:
    """
    Retorna as disciplinas de um curso.
    """
    course = CURSOS[course_id]

    return [
        DISCIPLINAS[subject_code]
        for subject_code in course["subjects"]
    ]
